name: environment
channels:
- conda-forge
- defaults
dependencies:
- python=3.11
- cartopy
- dask
- datashader
- gcsfs
- geoviews
- h5py
- holoviews
- hdf5
- hvplot
- jupyterlab
- kerchunk
- matplotlib
- netcdf4
- pip
- scipy
- xarray
- zarr
